### ISSUE TITLE
UnboundLocalError: local variable 'decoded_input_len' referenced before assignment

### ISSUE THREAD

**Issue by codebit23** [deepomicslab/Smart5UTR#1]
Hello, 
I re-run reimplement_Optimus5_on_egfp-m1p2dataset.ipynb, to generate a model. I used exact parameters, did not change anything. then I saved model and scaler.
When I run design_5UTR_by_Smart5UTR.ipynb, it shows the following error.
Do you know what could be the problem?
Thanks

UnboundLocalError                         Traceback (most recent call last)
Cell In[13], line 1
----> 1 optimized_seqs = optimize_sequences(autoencoder, scaler, p_seqs, iterations, coef)
      2 # optimized_seqs = optimize_sequences(autoencoder, scaler, bb, iterations, coef)

File ~/Smart5UTR/tutorials/../Smart5UTR/optimization.py:120, in optimize_sequences(model, scaler, init_seqs, iterations, coef)
    106 """
    107 Optimize the input sequences using the autoencoder model.
    108 
   (...)
    117     ae_seqs: A dictionary containing the optimized sequences and their output values.
    118 """
    119 # Split the autoencoder into encoder and decoder
--> 120 encoder, decoder, decoded_input_len = split_autoencoder(model)
    122 nbr_sequences = len(init_seqs)
    123 ae_seqs = {}

File ~/Smart5UTR/tutorials/../Smart5UTR/model.py:87, in split_autoencoder(model)
     84         necklayer_index = i
     86 # Create the decoder input with the shape found above
---> 87 decoder_input = keras.Input(shape=decoded_input_len)
     88 de = model.layers[decolayer_index](decoder_input)
     89 for layer in model.layers[necklayer_index:]:

UnboundLocalError: local variable 'decoded_input_len' referenced before assignment

**Comment by floretli** [comment]
> Hello, I re-run reimplement_Optimus5_on_egfp-m1p2dataset.ipynb, to generate a model. I used exact parameters, did not change anything. then I saved model and scaler. When I run design_5UTR_by_Smart5UTR.ipynb, it shows the following error. Do you know what could be the problem? Thanks
> 
> UnboundLocalError Traceback (most recent call last) Cell In[13], line 1 ----> 1 optimized_seqs = optimize_sequences(autoencoder, scaler, p_seqs, iterations, coef) 2 # optimized_seqs = optimize_sequences(autoencoder, scaler, bb, iterations, coef)
> 
> File ~/Smart5UTR/tutorials/../Smart5UTR/optimization.py:120, in optimize_sequences(model, scaler, init_seqs, iterations, coef) 106 """ 107 Optimize the input sequences using the autoencoder model. 108 (...) 117 ae_seqs: A dictionary containing the optimized sequences and their output values. 118 """ 119 # Split the autoencoder into encoder and decoder --> 120 encoder, decoder, decoded_input_len = split_autoencoder(model) 122 nbr_sequences = len(init_seqs) 123 ae_seqs = {}
> 
> File ~/Smart5UTR/tutorials/../Smart5UTR/model.py:87, in split_autoencoder(model) 84 necklayer_index = i 86 # Create the decoder input with the shape found above ---> 87 decoder_input = keras.Input(shape=decoded_input_len) 88 de = model.layers[decolayer_index](decoder_input) 89 for layer in model.layers[necklayer_index:]:
> 
> UnboundLocalError: local variable 'decoded_input_len' referenced before assignment

Dear codebit23,

Thank you for bringing this issue to my attention. Let me clarify what may be causing the error.

In this project, I reimplemented the original **Optimus 5-Prime** model from this [paper](https://www.nature.com/articles/s41587-019-0164-5) as a baseline, by retraining it on a different dataset using the code in `reimplement_Optimus5_on_egfp-m1p2dataset.ipynb`. **Smart5UTR** is a separate model I developed with a different architecture. I apologize that the documentation did not explicitly state this. 

Going forward, I will update the readme to distinguish Optimus 5-Prime and Smart5UTR more clearly. For your issue, please re-train Smart5UTR using the script `Smart5UTR/tutorials/train_Smart5UTR.py`, or download our trained model from google drive.

Let me know if following these steps to train and use Smart5UTR resolves the error you encountered. Thank you for the feedback - it will help me improve the project.

**Comment by codebit23** [comment]
Thanks. I figured out and closed the case.
